### ISSUE TITLE
PoseEstimation will crash

### ISSUE THREAD

**Issue by zhezhao1989** [Livox-SDK/LIO-Livox#1]
When I run PoseEstimation, will crash when ceres start to optimize, I guess it is related to pcl version, which pcl version, eigen version should be used?

or provide a docker file ?

**Comment by Livox-SDK** [comment]
Hi  zhhao1989

The Version we are using is PCL 1.8 and Eigen 3.3.9.
For now we don't have such a plan to provide a docker file

**Comment by zhezhao1989** [comment]
thanks for your reply, I forgot to ask, which ceres vesion should be used ?

**Comment by congphase** [comment]
Hi @zhezhao1989, have you solved this issue, by changing PCL version or something?

I'm facing the same issue.

My error log looks like this:

```
[rviz-3] process has died [pid 22724, exit code -6, cmd nice /opt/ros/kinetic/lib/rviz/rviz -d /home/ubuntu/catkin_ws/src/LIO-Livox/rviz_cfg/lio.rviz __name:=rviz __log:=/home/ubuntu/.ros/log/15806926-00ab-11ec-a7d8-0242ac110006/rviz-3.log].
log file: /home/ubuntu/.ros/log/15806926-00ab-11ec-a7d8-0242ac110006/rviz-3*.log
[PoseEstimation-2] process has died [pid 22703, exit code -11, cmd /home/ubuntu/catkin_ws/devel_isolated/lio_livox/lib/lio_livox/PoseEstimation __name:=PoseEstimation __log:=/home/ubuntu/.ros/log/15806926-00ab-11ec-a7d8-0242ac110006/PoseEstimation-2.log].
log file: /home/ubuntu/.ros/log/15806926-00ab-11ec-a7d8-0242ac110006/PoseEstimation-2*.log
```
in which PoseEstimation was the problem. The rviz one was because I ran the nodes remotely.

Can you share what you have experienced?

Thank you @zhezhao1989

**Comment by Daniyal-arch** [comment]
Have you solved you this issue ?  @congphase I am having the same pose estimation issue .

**Comment by congphase** [comment]
> Have you solved you this issue ? [@congphase](https://github.com/congphase) I am having the same pose estimation issue .

It's been almost 4 years since my last activity here so I hardly remember anything. You can take [my comment from another issue](https://github.com/Livox-SDK/LIO-Livox/issues/9#issuecomment-903278536) as reference. Hope it helps.
