### ISSUE TITLE
Something wrong with spin lidar(ouster64)

### ISSUE THREAD

**Issue by chengwei0427** [Livox-SDK/LIO-Livox#23]
Hi, friends,
I modify the feature extract moudle for my spin lidar--ouster,and the code is implemented based on lio_sam.
Now, the feature extract module is normal. And the result is good with the IMU_Mode is 0 and 1.
But there's something wrong when IMU_Mode is 2(Tightly Coupled IMU).

![2022-03-10 17-33-21屏幕截图](https://user-images.githubusercontent.com/20199999/157637777-cabce75e-590b-4ea1-954c-3290f4b5ca11.png)

As the picture above, when process "Frame:4654", the trajectory starts to shift.
The points and imu data record by ouster laser(OS1-64), so the transformation matrix of the laser and imu is the unit matrix. Other parameters are default.
The printing parameters are as follows:

![微信截图_20220310174838](https://user-images.githubusercontent.com/20199999/157637850-86240a33-a8e2-4c60-88dd-d78c79f48f8b.png)
![微信截图_20220310174913](https://user-images.githubusercontent.com/20199999/157637866-f1692880-2e02-4bed-b901-640bd5f2fc72.png)

What causes this? Someone has a similar situation?
Thanks again.

**Comment by chengwei0427** [comment]
Hi, 

I've tested  3 bags recored by my ouster OS1-64 lidar. Everything is ok at the first few hundred seconds, but after a period of time(500+/1000+ second), there is a drift after a bump or rotation, it's strange.

I'll test more bag.

Last, I uploaded the modified code  [here ](https://github.com/chengwei0427/LIO-Livox-modified)

**Comment by chengwei0427** [comment]
The problem solved. It's my mistake. The ALGO is very nice.

**Comment by liang0724s** [comment]
> Hi,
> 
> I've tested 3 bags recored by my ouster OS1-64 lidar. Everything is ok at the first few hundred seconds, but after a period of time(500+/1000+ second), there is a drift after a bump or rotation, it's strange.
> 
> I'll test more bag.
> 
> Last, I uploaded the modified code [here ](https://github.com/chengwei0427/LIO-Livox-modified)

Hi, @chengwei0427 
How is the performance in special scenarios like tunnel scene, dynamic urban scene, complex large scale urban scene, compared with [LIO-Livox](https://github.com/Livox-SDK/LIO-Livox)?

**Comment by chengwei0427** [comment]
Hi, @liang0724s 
1. No tunnel-related scenarios have been tested;
2. For `dynamic urban scene`, I've tested several sets of data collected while riding a scooter on the road, and the it works well;
3. For `complex large scale urban scene`, the maximum test scenario is 400X400 city roads;
