### ISSUE TITLE
[pcl::KdTreeFLANN::setInputCloud] Cannot create a KDTree with an empty input cloud!

### ISSUE THREAD

**Issue by onionysy** [Livox-SDK/LIO-Livox#30]
![2022-05-17 16-16-34屏幕截图](https://user-images.githubusercontent.com/55376216/168763874-506c8c10-1784-4289-8a9f-ed723c9aed06.png)
When we build a map on our own dataset, there are a large number of kdtree errors, as shown in the figure. Although this does not affect the operation of the program, the effect of mapping is poor Do you have any good suggestions?

**Comment by liang0724s** [comment]
This error is most likely caused by the failure to detect feature points(Corner---1, Surf---2, NonFeature---3) in current frame.
You can check the node "LidarFeatureExtractor".

**Comment by liyui1104** [comment]
I have the same issue when I try to run the following codes.
```
roslaunch livox_ros_driver2 livox_lidar_msg_HAP.launch
roslaunch lio_livox hap.launch
```
My errors:
```
[pcl::KdTreeFLANN::setInputCloud] Cannot create a KDTree with an empty input cloud!
[ INFO] [1667715070.825824110]: Frame: 607

[pcl::KdTreeFLANN::setInputCloud] Cannot create a KDTree with an empty input cloud!
[ INFO] [1667715070.925633590]: Frame: 608
...
```

My hap_config.yaml:
```
%YAML:1.0

# switches
Lidar_Type: 1    # 1-hap
Used_Line: 6    # lines used for lio, set to 1~6
Feature_Mode: 0    # 0(false) or 1(true)
NumCurvSize: 2
DistanceFaraway: 100 # [m]  <DistanceFaraway near / >DistanceFaraway far
NumFlat: 3 # nums of one part's flat feature
PartNum: 150 # nums of one scan's parts
FlatThreshold: 0.02 # cloud curvature threshold of flat feature
BreakCornerDis: 1 # break distance of break points
LidarNearestDis: 1.0 # if(depth < LidarNearestDis) do not use this point 
KdTreeCornerOutlierDis: 0.2 # corner filter threshold
Use_seg: 1 # use segment algorithm
map_skip_frame: 2
```
My HAP_config.json:
```
{
	"lidar_summary_info" : {
			"lidar_type": 8
	},
	"HAP": {
		"lidar_net_info" : {
			"cmd_data_port": 56000,
			"push_msg_port": 0,
			"point_data_port": 57000,
			"imu_data_port": 58000,
			"log_data_port": 59000
		},
		"host_net_info" : {
			"cmd_data_ip" : "192.168.1.50",
			"cmd_data_port": 56000,
			"push_msg_ip": "",
			"push_msg_port": 0,
			"point_data_ip": "192.168.1.50",
			"point_data_port": 57000,
			"imu_data_ip" : "192.168.1.50",
			"imu_data_port": 58000,
			"log_data_ip" : "",
			"log_data_port": 59000
		}
	},
	"lidar_configs" : [
		{
			"ip" : "192.168.1.100",
			"pcl_data_type" : 1,
			"pattern_mode" : 0,
			"blind_spot_set" : 50,
			"extrinsic_parameter" : {
				"roll": 0.0,
				"pitch": 0.0,
				"yaw": 0.0,
				"x": 0,
				"y": 0,
				"z": 0
			}
		}
	]
}

```

Any solution for it?
Thanks in addvance!

**Comment by HowoongJun** [comment]
This is because of empty corner feature. 
You can check LidarFeatureExtractor.cpp as @liang0724s said. 
If you are using HAP, "FeatureExtract_with_segment_hap()" function has no corner detecting part. 
This is not a fundamental solution but I referenced "FeatureExtract_with_segment()" function to edit "~~_hap()" function. 
Again, this is not a fundamental solution but it will remove that error.

**Comment by abhishekt711** [comment]
> 

solved the error but after running some frame this error is coming in which scanregistration process is died
![Screenshot from 2023-08-10 00-12-49](https://github.com/Livox-SDK/LIO-Livox/assets/36338604/c828c038-be72-4702-bd2a-b26e01185098)

**Comment by suyuzhu** [comment]
> > 
> 
> solved the error but after running some frame this error is coming in which scanregistration process is died ![Screenshot from 2023-08-10 00-12-49](https://user-images.githubusercontent.com/36338604/259514214-c828c038-be72-4702-bd2a-b26e01185098.png)

Same with me . Have you solved it ?
