### ISSUE TITLE
how to save the map?

### ISSUE THREAD

**Issue by LouxiDahu** [Livox-SDK/LIO-Livox#47]

**Comment by wzt991101** [comment]
I have  the same problem. Have you solved this problem？

**Comment by LouxiDahu** [comment]
> 

自己写一段保存点云的代码就可以。

**Comment by wzt991101** [comment]
***@***.***



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年06月13日 09:59 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Livox-SDK/LIO-Livox] how to save the map? (Issue #47) |

自己写一段保存点云的代码就可以。

**Comment by abhishekt711** [comment]
> 自己写一段保存点云的代码就可以。

Hey did you solved this problem? can u please suggest where to modify in the code to save the map in pcd file.

**Comment by lonlonago** [comment]
save map code ; wechat 394467238
