### ISSUE TITLE
message not compatible when using lvx-converted bag file

### ISSUE THREAD

**Issue by sume-cn** [Livox-SDK/LIO-Livox#5]
1.download lvx file from 'https://www.livoxtech.com/downloads', Livox Horizon Point Cloud Data 1 2020-03-18
2.use  ‘roslaunch livox_ros_driver lvx_to_rosbag.launch’ to convert the lvx file to bag file
3.run LIO-livox and rosbag play, error reported as: 
[RUNNING]  Bag Time:   3036.199661   Duration: 0.000000 / 94.499459            
[ERROR] [1628220411.045738465]: Client [/ScanRegistration] wants topic /livox/lidar to have datatype/md5sum [livox_ros_driver/CustomMsg/e4d6829bdfe657cb6c21a746c86b21a6], but our version has [sensor_msgs/PointCloud2/1158d486dd51d683ce2f1be655c3c181]. Dropping connection.
 [RUNNING]  Bag Time:   3036.199742   Duration: 0.000081 / 94.499459 
....

**Comment by sume-cn** [comment]
problem solved, when converting lvx file, two parameters must be specified like:
roslaunch livox_ros_driver lvx_to_rosbag.launch lvx_file_path:=/home/aaa/Horizon_road.lvx xfer_format:=1 imu_bag:=true
![20210806-143059](https://user-images.githubusercontent.com/34541204/128466656-dd787e12-863d-4de7-a117-67aae5bee9fd.png)

**Comment by arjunskumar** [comment]
@sume-cn Could you mention your PCL and Eigen version. I have trouble running the package

**Comment by sume-cn** [comment]
> @sume-cn Could you mention your PCL and Eigen version. I have trouble running the package

sorry, I just noticed your reply today.
all components are come along with ubuntu 18 and ROS melodic.

**Comment by arjunskumar** [comment]
@sume-cn Yes, able to work it properly. Thanks
