### ISSUE TITLE
Download for Rosbag

### ISSUE THREAD

**Issue by PanterSoft** [Livox-SDK/LIO-Livox#67]
Hello is there a Download for The Rosbag used as exmple ?

**Comment by ManChrys** [comment]
Hello @PanterSoft ,

i think you can download some samples from [https://isas-server.iar.kit.edu/lidardataset/LiLi-OM-Data/Livox_Horizon/](url), which  are samples from the [https://github.com/KIT-ISAS/lili-om](url)

**Comment by PanterSoft** [comment]
Thanks for the links. I found the Datasets
