### ISSUE TITLE
How do you align the point cloud with Google Maps?

### ISSUE THREAD

**Issue by suyuzhu** [Livox-SDK/LIO-Livox#69]
As far as I know, GPS positioning in tunnels is not accurate. So, how do you align the point cloud with Google Maps in the tunnel scene? What software do you recommend? Thanks a lot.

![image](https://github.com/Livox-SDK/LIO-Livox/assets/66911600/401d5a6d-528e-48d4-9590-27f554f31f0a)

**Comment by ManChrys** [comment]
hello @suyuzhu ,

you can download, for example, qgis (which is free) , add google maps plugin (HCMGIS), so you can add google maps as background and then import your pointcloud in it. When you import your pointcloud qgis convert it to a format which is lighter than the original pointcloud so you can interact smoothly.
