### ISSUE TITLE
测试结果路径高程没有闭合，请问可能是什么原因?

### ISSUE THREAD

**Issue by colinlin1982** [Livox-SDK/LIO-Livox#7]
我们使用默认的配置参数，以15km/h的速度，绕一个街区进行了测试。从最终的路径看，水平方向基本重合，但高程没有闭合，请问可能有哪些原因？

运行配置： MS Surface Pro i7/Ubuntu 18.04/PCL 1.8/Eigen 3.3.9
运行过程中点云融合延时比较严重，但是最终有正常结束。

路径截图：
![rviz_screenshot_2021_08_09-18_35_23](https://user-images.githubusercontent.com/13325086/128695219-216aa52c-4d2a-419c-86a7-8a255372ed3a.png)

**Comment by Livox-SDK** [comment]
Hi colinlin1982,

高程没有闭合这个现象应该是由于误差引起的 由于这一套代码是没有回环检测的；误差会持续累加；最终导致计算的结果有偏移。 您可以基于这套代码开发； 做一个回环检测从而优化结果的准确性

运行延迟严重这个问题我推测应该是电脑性能不够引起的； 建议在到一个性能和散热好一些的台式机上运行

**Comment by colinlin1982** [comment]
> Hi colinlin1982,
> 
> 高程没有闭合这个现象应该是由于误差引起的 由于这一套代码是没有回环检测的；误差会持续累加；最终导致计算的结果有偏移。 您可以基于这套代码开发； 做一个回环检测从而优化结果的准确性
> 
> 运行延迟严重这个问题我推测应该是电脑性能不够引起的； 建议在一个性能和散热好一些的台式机上运行

感谢您的回复！请问针对回环检测，您能否推荐一个开源算法，比较适合应用于本项目生成的路径？

**Comment by zxd123** [comment]
> > Hi colinlin1982,
> > 高程没有闭合这个现象应该是由于误差引起的 由于这一套代码是没有回环检测的；误差会持续累加；最终导致计算的结果有偏移。 您可以基于这套代码开发； 做一个回环检测从而优化结果的准确性
> > 运行延迟严重这个问题我推测应该是电脑性能不够引起的； 建议在一个性能和散热好一些的台式机上运行
> 
> 感谢您的回复！请问针对回环检测，您能否推荐一个开源算法，比较适合应用于本项目生成的路径？

老哥或许你可以试试[Scan Context](https://github.com/irapkaist/scancontext)？期待你的测试结果

**Comment by SiyuanHuang95** [comment]
可以尝试下这个开源项目，已经加入了回环检测、地面约束等：https://github.com/PJLab-ADG/Livox-Mapping
